# Machine Learning Example with Scikit-Learn

Following is an example of a classification with a random forest classifier from the sk-learn library. It is evaluated, and the confusion matrix is shown.

First, import the necessary machine learning libraries:

In [1]:
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix

/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


Next, import the open data set of digits from sk-learn.

In [2]:
digits = datasets.load_digits()
print(digits.data)
print(digits.target)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]


Then, split it up into features of the data set (digits.data) and the results (digits.target).

In [3]:
X, y = digits.data, digits.target

As a further step the random forest classifier is defined and trained.

In [4]:
rfc = RandomForestClassifier(n_estimators=5, max_depth=None, min_samples_split=2, random_state=0)

In [5]:
rfc.fit(X, y)
scores = cross_val_score(rfc, X, y, cv=5)
scores.mean()    

0.8676621323020811

Last but not least, the classifier is tested on the original data set for performance and correctness of the classification.

In [6]:
predictions = rfc.predict(digits.data[:])
print(predictions)

[0 1 2 ... 8 9 8]


In [7]:
print(digits.target[:])

[0 1 2 ... 8 9 8]


In [8]:
print(confusion_matrix(digits.target, predictions, labels =[0,1,2,3,4,5,6,7,8,9] ))

[[178   0   0   0   0   0   0   0   0   0]
 [  0 182   0   0   0   0   0   0   0   0]
 [  0   0 176   0   0   1   0   0   0   0]
 [  0   0   0 182   0   1   0   0   0   0]
 [  0   1   0   0 179   1   0   0   0   0]
 [  0   0   0   0   0 181   0   1   0   0]
 [  0   0   0   0   1   0 180   0   0   0]
 [  0   1   0   0   0   0   0 178   0   0]
 [  0   0   1   0   0   0   0   0 173   0]
 [  0   0   0   0   0   1   0   0   0 179]]
