# Neural Network Example with Keras

Here, you can find an example of a multi-class classification with a small neural network constructed with the Keras library. As a data set the Iris data set from sklearn is used.

In [1]:
import numpy as np
import keras
from sklearn import datasets
from sklearn import metrics
from numpy import argmax
from keras.utils import to_categorical

/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


Loading the standard Iris dataset and having a look at the values

In [2]:
iris = datasets.load_iris()
print(iris.data)
print(iris.target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

For classification we need the features (X) and the Flag (y) separated. Also, the outcome has to be categorical (one hot encoded). The data set is then split up into train and test to confirm that the neural network is functioning properly.

In [3]:
X, y = iris.data, iris.target

In [4]:
encoded = to_categorical(y)
print(encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, encoded, random_state=0)

Next is the training of the neural network with two hidden layers.

In [11]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
import numpy

# fix random seed for reproducibility
numpy.random.seed(3)

# create model
model = Sequential()
model.add(Dense(20, input_dim=4, kernel_initializer='glorot_uniform', activation='relu'))
Dropout(0.5)
model.add(Dense(10, kernel_initializer='glorot_uniform', activation='softmax'))
Dropout(0.5)
model.add(Dense(3, kernel_initializer='glorot_uniform', activation='softmax'))
# Compile model
optimizer = keras.optimizers.Adam(lr=0.001)
model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
# Fit the model
model.fit(X_train, y_train, epochs=100, batch_size=20)

Epoch 1/100
112/112 [==============================] - 4s 32ms/step - loss: 1.1056 - acc: 0.3661
Epoch 2/100
112/112 [==============================] - 0s 289us/step - loss: 1.0939 - acc: 0.3661
Epoch 3/100
112/112 [==============================] - 0s 631us/step - loss: 1.0800 - acc: 0.3661
Epoch 4/100
112/112 [==============================] - 0s 1ms/step - loss: 1.0640 - acc: 0.3661
Epoch 5/100
112/112 [==============================] - 0s 632us/step - loss: 1.0476 - acc: 0.3661
Epoch 6/100
112/112 [==============================] - 0s 1ms/step - loss: 1.0312 - acc: 0.3661
Epoch 7/100
112/112 [==============================] - 0s 726us/step - loss: 1.0153 - acc: 0.3661
Epoch 8/100
112/112 [==============================] - 0s 827us/step - loss: 0.9996 - acc: 0.4732
Epoch 9/100
112/112 [==============================] - 0s 779us/step - loss: 0.9827 - acc: 0.6607
Epoch 10/100
112/112 [==============================] - 0s 1ms/step - loss: 0.9657 - acc: 0.6964
Epoch 11/100
112/112 [====

Epoch 84/100
112/112 [==============================] - 0s 822us/step - loss: 0.4380 - acc: 0.9732
Epoch 85/100
112/112 [==============================] - 0s 821us/step - loss: 0.4338 - acc: 0.9732
Epoch 86/100
112/112 [==============================] - 0s 860us/step - loss: 0.4288 - acc: 0.9732
Epoch 87/100
112/112 [==============================] - 0s 892us/step - loss: 0.4254 - acc: 0.9732
Epoch 88/100
112/112 [==============================] - 0s 830us/step - loss: 0.4219 - acc: 0.9732
Epoch 89/100
112/112 [==============================] - 0s 881us/step - loss: 0.4186 - acc: 0.9732
Epoch 90/100
112/112 [==============================] - 0s 874us/step - loss: 0.4139 - acc: 0.9732
Epoch 91/100
112/112 [==============================] - 0s 1ms/step - loss: 0.4097 - acc: 0.9643
Epoch 92/100
112/112 [==============================] - 0s 779us/step - loss: 0.4066 - acc: 0.9643
Epoch 93/100
112/112 [==============================] - 0s 763us/step - loss: 0.4025 - acc: 0.9732
Epoch 94/100

As you will see, the neural network was able to predict 97 % of the test data correctly.

In [12]:
predictions = model.predict(X_test)
predictions = np.argmax(predictions, axis=1) 
y_test = np.argmax(y_test, axis=1)
print(metrics.accuracy_score(y_test, predictions))
print(metrics.confusion_matrix(y_test, predictions))

0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
